[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"


[project]
name = "jsonreflow"
dynamic = ["version"]
description = "Indented JSON, but with one-line arrays or objects if they fit a desired line length."
readme = "README.md"
requires-python = ">= 3.8"
authors = [
  {name = "Stefaan Lippens", email = "soxofaan@gmail.com"},
]
license = "MIT"
license-files = ["LICENSE.txt"]
keywords = ["JSON", "serialization"]
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
  "License :: OSI Approved :: MIT License",
  "Topic :: File Formats :: JSON",
  "Topic :: Utilities",
]


[project.urls]
Repository = "https://github.com/soxofaan/jsonreflow"
Changelog = "https://github.com/soxofaan/jsonreflow/blob/main/CHANGELOG.md"


[project.optional-dependencies]
dev = [
    "pytest>=8.3",
]


[project.scripts]
jsonreflow = "jsonreflow.cli:main"



[tool.hatch.build.targets.wheel]
packages = ["src/jsonreflow"]

[tool.hatch.build.targets.sdist]
include = [
  "src/",
  "tests/",
]

[tool.hatch.version]
path = "src/jsonreflow/__init__.py"


[tool.ruff.lint]
select = [
  # pycodestyle
  "E",
  # Pyflakes
  "F",
  # pyupgrade
  "UP",
  # flake8-bugbear
  "B",
  # flake8-simplify
  "SIM",
  # isort
  "I",
]
